# PostgreSQL Database Configuration
#spring.datasource.url=jdbc:postgresql://localhost:5432/library
spring.datasource.url=jdbc:p6spy:postgresql://localhost:5432/library
spring.datasource.username=admin
spring.datasource.password=admin123
#spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.driver-class-name=com.p6spy.engine.spy.P6SpyDriver


# JPA/Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Logging
logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.hibernate.orm.jdbc.bind=TRACE
